# Generated by Django 2.1.2 on 2018-12-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captionHeading', models.CharField(max_length=264, unique=True)),
                ('captionDetails', models.CharField(max_length=264)),
                ('imageUrl', models.CharField(max_length=264)),
            ],
        ),
    ]
